### ISSUE TITLE
Search text is lost when going to full results

### ISSUE THREAD

**Issue by Splaktar** [GoogleChrome/browser-bug-search#17]
Pressing enter or selecting ‘SEE FULL RESULTS’ brings you to a search page but loses your search text (on Chrome).

Open, type search
<img width="600" alt="screen shot 2017-04-26 at 1 33 35 pm" src="https://cloud.githubusercontent.com/assets/3506071/25448338/18cf473c-2a86-11e7-9a96-2c6bba7b75c7.png">

Press Enter or click 'SEE FULL RESULTS' button.
In this example, it opens https://developers.google.com/web/feedback/browser-bug-searcher?q=css%20attribute%20selectors but the search text and results are empty.
<img width="888" alt="screen shot 2017-04-26 at 1 44 03 pm" src="https://cloud.githubusercontent.com/assets/3506071/25448436/778fbf68-2a86-11e7-8fa1-27fac4e315b8.png">

It would be expected that the search text (and related results) would be displayed.

**Comment by ebidel** [comment]
Thanks for reporting! This is a recent-ish known issue. Haven't gotten around to fixing it on developers.google.com just yet.

**Comment by ebidel** [comment]
Should be fixed https://github.com/google/WebFundamentals/pull/4481 :)
