### ISSUE TITLE
npm install (error npm run deps; missing)

### ISSUE THREAD

**Issue by moumen-soliman** [GoogleChrome/browser-bug-search#21]
On run npm install there is `npm run deps;` error in terminal

**Comment by moumen-soliman** [comment]
its solved on #23

**Comment by hackhnaton1994** [comment]
From 1639511242778766481@xxx Fri Jul 19 18:09:23 +0000 2019
X-GM-THRID: 1639508997605108961
X-Gmail-Labels: Peti masuk,Penting
Delivered-To: founderhackhnaton@gmail.com
Received: by 2002:a67:13c7:0:0:0:0:0 with SMTP id 190csp3978988vst;
        Fri, 19 Jul 2019 11:09:23 -0700 (PDT)
X-Google-Smtp-Source: APXvYqwfksAkQXAXydOOqC+UDIIyctF2t/KK+bxOC6iUgzz6GKmIP3DJb7zTFQTwYxWPBokCxJXa
X-Received: by 2002:a17:902:d892:: with SMTP id b18mr54576893plz.165.1563559763869;
        Fri, 19 Jul 2019 11:09:23 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1563559763; cv=none;
        d=google.com; s=arc-20160816;
        b=z4YzpWc+FDhXVkr6PpMME6Ksiv+R/cIRnRIEYA8cLOIWb82qzw9pcgfJByOigeEmaO
         L///O6FitgruYAXGJT0V2mkHmZ8KKPw/BDNVUq9n/1J7Y2kNp3Zs4+BRFfUMCMQwaQd1
         Ek6WdgZfGJ1VEQYABiyv65XsH7L31gurLyjUJK9nTqAFsGRGw29n6Dwm/owThbGhQl91
         L3xUne52EULK/5hoExpi77jU3qtcnkGMNDKhGQJtysUjOdKPDCLPGDH7K7IyJ+3iSwYu
         Vx4Jcg73RUokP9C4zrCnFJwT0Ht2mPl+cyTLJ/DqEJvXLwS+/3dsoJCgvE0N5L5NM0yH
         zbaw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=dkim-signature:auto-submitted:content-transfer-encoding
         :mime-version:subject:references:in-reply-to:message-id:to:reply-to
         :from:date;
        bh=fRnJl5/M3laRqG5fKU6HNvIRw9qI0LF1eznFdWeWbw4=;
        b=xVgpeHCUpyyGd8S3bFBSf18FGTGNCtKvmVaMFm5KSR8vs9iiCbo7eK2Zmfokmkjxbg
         QbYkQINNxqxXqlojZH8NHKCBwU4tGCLQyNLClydpWWXCfIN8akuYCeZx3nBP71/5zb+E
         tvtFPL2FCVzdTvZ8C6ETKo0SBk99HzGI9M8tK+crLJuFtXcgohT8VkXvZSXV0FSd+cdb
         S5CkxpdO0ATSMUhM7LDz2/mwqM/QdgnzKZGzgKQQRYoFXWay9o3bN+/b7nmhx9vY9jGG
         3CWk+aoLu92D+x7LsK/YYNZL7md9T0L47h+FslmZsFLU4MbC/jvgleen0mQWVXNOUXhs
         bT7w==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@hackerone.com header.s=zendesk1 header.b=JyQELbHZ;
       spf=pass (google.com: domain of support@hackerone.com designates 192.161.151.3 as permitted sender) smtp.mailfrom=support@hackerone.com;
       dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=hackerone.com
Return-Path: <support@hackerone.com>
Received: from outbyoip3.pod13.usw2.zdsys.com (outbyoip3.pod13.usw2.zdsys.com. [192.161.151.3])
        by mx.google.com with ESMTPS id f1si35069pjw.100.2019.07.19.11.09.23
        for <founderhackhnaton@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 19 Jul 2019 11:09:23 -0700 (PDT)
Received-SPF: pass (google.com: domain of support@hackerone.com designates 192.161.151.3 as permitted sender) client-ip=192.161.151.3;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@hackerone.com header.s=zendesk1 header.b=JyQELbHZ;
       spf=pass (google.com: domain of support@hackerone.com designates 192.161.151.3 as permitted sender) smtp.mailfrom=support@hackerone.com;
       dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=hackerone.com
Received: from zendesk.com (unknown [10.210.105.166])
	by outbyoip3.pod13.usw2.zdsys.com (Postfix) with ESMTP id 4C8461805181
	for <founderhackhnaton@gmail.com>; Fri, 19 Jul 2019 18:09:23 +0000 (UTC)
Date: Fri, 19 Jul 2019 18:09:23 +0000
From: HackerOne <support@hackerone.com>
Reply-To: HackerOne <support@hackerone.com>
To: FOUNDER HACKHNATON <founderhackhnaton@gmail.com>
Message-ID: <090546L8ZW_5d320753f643_aa03fa5f98bcf20285721_sprut@zendesk.com>
In-Reply-To: <CADRaA4zZPkBQ++Auufm-V_WnPZn_toJZ8qT1b8JRwGUF8Z=A8Q@mail.gmail.com>
 <090546L8ZW_5d31ff20df150_5853fd2f6cbcf24268126_sprut@zendesk.com>
References: <090546L8ZW@zendesk.com>
 <CADRaA4zZPkBQ++Auufm-V_WnPZn_toJZ8qT1b8JRwGUF8Z=A8Q@mail.gmail.com>
Subject: [HackerOne] Re: New Directory Entry
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5d32075347a7b_aa03fa5f98bcf20285897";
 charset=utf-8
Content-Transfer-Encoding: 7bit
X-Delivery-Context: event-id-696994894551
Auto-Submitted: auto-generated
X-Auto-Response-Suppress: All
X-Mailer: Zendesk Mailer
X-Zendesk-From-Account-Id: 4f636ff
X-Zendesk-Message-Id: <090546L8ZW_5d320753f643_aa03fa5f98bcf20285721_sprut@zendesk.com>
DKIM-Signature:  v=1; a=rsa-sha256; c=relaxed/relaxed; d=hackerone.com;
 q=dns/txt; s=zendesk1; t=1563559763;
 bh=fRnJl5/M3laRqG5fKU6HNvIRw9qI0LF1eznFdWeWbw4=;
 h=from:reply-to:to:message-id:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding;
 b=JyQELbHZeErgiu+b/JEnUkkl4zOwOgdb4+vjS2ZlTs/mABjBuiHhtzs1hZXj2VllGeC5Wc/zsQcDaIYtAoaJ7iWscn3BPiMnS6/kuoT8YZnqQZaxSv1vMjXy5SENYiPJDCOLSl8CLJIX6M5qXRgTDYBoDfGq/nnI8NGhdZsKLIjHvAW7AO9eJUxIuOxe6Pv72x0xKFqfG0Jx/oP1u/ExFw5B/KwutjFzoYNmpdpWtfrccLXF2RXupL4+Jafe2ZZDo4MAK7jVpWiuHDB7ZE63zULo36XjWjwTETulVTbU7fn1q89sf+amnT3UaldsdRVkaD27AW/rktH4WQaDU6QnHw==
