### ISSUE TITLE
localhost site can get other site's cookie

### ISSUE THREAD

**Issue by temool** [GoogleChrome/browser-bug-search#24]
I started my site on localhost:8080，it fetches data from url(http://demo.com/api/xxxxx)，I found I can get http://demo.com cookie. But when I use axios.js to send my request，I can't get http://demo.com cookie.
<img width="1368" alt="wechatimg5" src="https://user-images.githubusercontent.com/19208354/46590473-1f3a3f80-cae6-11e8-84d5-31c14814aad1.png">

**Comment by ebidel** [comment]
This is not the appropriate issue tracker.
